name: Install PyMuPDF on Windows
if: matrix.os == 'windows-2019'
      run: |
        [bool] $vsSetupExists = $null -ne (Get-Command Get-VSSetupInstance -ErrorAction SilentlyContinue)
        if (!$vsSetupExists)
        {
          Write-Verbose "Installing the VSSetup module..."
          Install-Module VSSetup -Scope CurrentUser -Force
        }
        [string] $visualStudioInstallationPath = (Get-VSSetupInstance | Select-VSSetupInstance -Latest -Require Microsoft.Component.MSBuild).InstallationPath
        $env:PYMUPDF_SETUP_DEVENV = (Get-ChildItem $visualStudioInstallationPath -Recurse -Filter "DevEnv.exe" | Select-Object -First 1).FullName
        curl -OL https://github.com/pymupdf/PyMuPDF/archive/refs/tags/1.20.2.zip
        tar -xf 1.20.2.zip
        cd PyMuPDF-1.20.2
        python setup.py install
        cd ..
        rm -f 1.20.2.zip
        rd -r -fo PyMuPDF-1.20.2
